/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: s48h5mVi5f22yNVro3eX55
// Component: OpB0Hx1q8CKr

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: s48h5mVi5f22yNVro3eX55/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: s48h5mVi5f22yNVro3eX55/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: s48h5mVi5f22yNVro3eX55/projectcss
import sty from "./PlasmicNewPage2.module.css"; // plasmic-import: OpB0Hx1q8CKr/css

import Icon5Icon from "./icons/PlasmicIcon__Icon5"; // plasmic-import: rPN5ebI8LRBJ/icon
import Icon6Icon from "./icons/PlasmicIcon__Icon6"; // plasmic-import: f-MT9TvUNlfV/icon
import Icon8Icon from "./icons/PlasmicIcon__Icon8"; // plasmic-import: g5gp1myXY9Mc/icon

createPlasmicElementProxy;

export type PlasmicNewPage2__VariantMembers = {};
export type PlasmicNewPage2__VariantsArgs = {};
type VariantPropType = keyof PlasmicNewPage2__VariantsArgs;
export const PlasmicNewPage2__VariantProps = new Array<VariantPropType>();

export type PlasmicNewPage2__ArgsType = {};
type ArgPropType = keyof PlasmicNewPage2__ArgsType;
export const PlasmicNewPage2__ArgProps = new Array<ArgPropType>();

export type PlasmicNewPage2__OverridesType = {
  root?: Flex__<"div">;
  animatedPortfolioWebsite?: Flex__<"div">;
  projectPage?: Flex__<"div">;
  container?: Flex__<"div">;
  container2?: Flex__<"div">;
  container3?: Flex__<"div">;
  container4?: Flex__<"div">;
  container5?: Flex__<"div">;
  container6?: Flex__<"div">;
  container7?: Flex__<"div">;
  container8?: Flex__<"div">;
  container9?: Flex__<"div">;
  container10?: Flex__<"div">;
  container11?: Flex__<"div">;
  container12?: Flex__<"div">;
  container13?: Flex__<"div">;
  container14?: Flex__<"div">;
  container15?: Flex__<"div">;
  container16?: Flex__<"div">;
  container17?: Flex__<"div">;
  container18?: Flex__<"div">;
  container19?: Flex__<"div">;
  container20?: Flex__<"div">;
  container21?: Flex__<"div">;
  container22?: Flex__<"div">;
  container23?: Flex__<"div">;
  container24?: Flex__<"div">;
  container25?: Flex__<"div">;
  container26?: Flex__<"div">;
  container27?: Flex__<"div">;
  container28?: Flex__<"div">;
  container29?: Flex__<"div">;
  container30?: Flex__<"div">;
  container31?: Flex__<"div">;
  container32?: Flex__<"div">;
  container33?: Flex__<"div">;
  container34?: Flex__<"div">;
  container35?: Flex__<"div">;
  container36?: Flex__<"div">;
  container37?: Flex__<"div">;
  container38?: Flex__<"div">;
  container39?: Flex__<"div">;
  container40?: Flex__<"div">;
  container41?: Flex__<"div">;
  container42?: Flex__<"div">;
  container43?: Flex__<"div">;
  container44?: Flex__<"div">;
  container45?: Flex__<"div">;
  container46?: Flex__<"div">;
  container47?: Flex__<"div">;
  container48?: Flex__<"div">;
  container49?: Flex__<"div">;
  container50?: Flex__<"div">;
  container51?: Flex__<"div">;
  container52?: Flex__<"div">;
  container53?: Flex__<"div">;
  container54?: Flex__<"div">;
  container55?: Flex__<"div">;
  container56?: Flex__<"div">;
  container57?: Flex__<"div">;
  container58?: Flex__<"div">;
  container59?: Flex__<"div">;
  container60?: Flex__<"div">;
  container61?: Flex__<"div">;
  container62?: Flex__<"div">;
  container63?: Flex__<"div">;
  container64?: Flex__<"div">;
  container65?: Flex__<"div">;
  container66?: Flex__<"div">;
  container67?: Flex__<"div">;
  container68?: Flex__<"div">;
  container69?: Flex__<"div">;
  container70?: Flex__<"div">;
  container71?: Flex__<"div">;
  container72?: Flex__<"div">;
  container73?: Flex__<"div">;
  container74?: Flex__<"div">;
  header?: Flex__<"div">;
  link?: Flex__<"div">;
  button?: Flex__<"div">;
  projectPage2?: Flex__<"div">;
  container75?: Flex__<"div">;
  heading1?: Flex__<"div">;
  container76?: Flex__<"div">;
  container77?: Flex__<"div">;
  container78?: Flex__<"div">;
  paragraph?: Flex__<"div">;
  paragraph2?: Flex__<"div">;
  container79?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  container80?: Flex__<"div">;
  paragraph3?: Flex__<"div">;
  paragraph4?: Flex__<"div">;
  container81?: Flex__<"div">;
  container82?: Flex__<"div">;
  paragraph5?: Flex__<"div">;
  paragraph6?: Flex__<"div">;
  container83?: Flex__<"div">;
  paragraph7?: Flex__<"div">;
  paragraph8?: Flex__<"div">;
  paragraph9?: Flex__<"div">;
  foundationalArchitecturalStudiesExploringSpati?: Flex__<"div">;
  container84?: Flex__<"div">;
  container85?: Flex__<"div">;
  projectPage3?: Flex__<"div">;
  container86?: Flex__<"div">;
  projectPage4?: Flex__<"div">;
  container87?: Flex__<"div">;
  projectPage5?: Flex__<"div">;
  container88?: Flex__<"div">;
  projectPage6?: Flex__<"div">;
  container89?: Flex__<"div">;
  projectPage7?: Flex__<"div">;
  container90?: Flex__<"div">;
  projectPage8?: Flex__<"div">;
  container91?: Flex__<"div">;
  container92?: Flex__<"div">;
  heading3?: Flex__<"div">;
  container93?: Flex__<"div">;
  text?: Flex__<"div">;
  text2?: Flex__<"div">;
  text3?: Flex__<"div">;
  text4?: Flex__<"div">;
  container94?: Flex__<"div">;
  heading4?: Flex__<"div">;
  list?: Flex__<"div">;
  listItem?: Flex__<"div">;
  projectPage9?: Flex__<"div">;
  projectPage10?: Flex__<"div">;
  explorationOfBasicSpatialConceptsAndArchitec?: Flex__<"div">;
  listItem2?: Flex__<"div">;
  projectPage11?: Flex__<"div">;
  projectPage12?: Flex__<"div">;
  studyOfProportionScaleAndHumanExperienceI?: Flex__<"div">;
  listItem3?: Flex__<"div">;
  projectPage13?: Flex__<"div">;
  projectPage14?: Flex__<"div">;
  developmentOfRepresentationTechniquesAndDesig?: Flex__<"div">;
  listItem4?: Flex__<"div">;
  projectPage15?: Flex__<"div">;
  projectPage16?: Flex__<"div">;
  focusOnUnderstandingMaterialityAndConstructio?: Flex__<"div">;
};

export interface DefaultNewPage2Props {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicNewPage2__RenderFunc(props: {
  variants: PlasmicNewPage2__VariantsArgs;
  args: PlasmicNewPage2__ArgsType;
  overrides: PlasmicNewPage2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"animatedPortfolioWebsite"}
            data-plasmic-override={overrides.animatedPortfolioWebsite}
            className={classNames(projectcss.all, sty.animatedPortfolioWebsite)}
          >
            <div
              data-plasmic-name={"projectPage"}
              data-plasmic-override={overrides.projectPage}
              className={classNames(projectcss.all, sty.projectPage)}
            >
              <div
                data-plasmic-name={"container"}
                data-plasmic-override={overrides.container}
                className={classNames(projectcss.all, sty.container)}
              >
                <div
                  data-plasmic-name={"container2"}
                  data-plasmic-override={overrides.container2}
                  className={classNames(projectcss.all, sty.container2)}
                />

                <div
                  data-plasmic-name={"container3"}
                  data-plasmic-override={overrides.container3}
                  className={classNames(projectcss.all, sty.container3)}
                />

                <div
                  data-plasmic-name={"container4"}
                  data-plasmic-override={overrides.container4}
                  className={classNames(projectcss.all, sty.container4)}
                />

                <div
                  data-plasmic-name={"container5"}
                  data-plasmic-override={overrides.container5}
                  className={classNames(projectcss.all, sty.container5)}
                />

                <div
                  data-plasmic-name={"container6"}
                  data-plasmic-override={overrides.container6}
                  className={classNames(projectcss.all, sty.container6)}
                />

                <div
                  data-plasmic-name={"container7"}
                  data-plasmic-override={overrides.container7}
                  className={classNames(projectcss.all, sty.container7)}
                />

                <div
                  data-plasmic-name={"container8"}
                  data-plasmic-override={overrides.container8}
                  className={classNames(projectcss.all, sty.container8)}
                />

                <div
                  data-plasmic-name={"container9"}
                  data-plasmic-override={overrides.container9}
                  className={classNames(projectcss.all, sty.container9)}
                />

                <div
                  data-plasmic-name={"container10"}
                  data-plasmic-override={overrides.container10}
                  className={classNames(projectcss.all, sty.container10)}
                />

                <div
                  data-plasmic-name={"container11"}
                  data-plasmic-override={overrides.container11}
                  className={classNames(projectcss.all, sty.container11)}
                />

                <div
                  data-plasmic-name={"container12"}
                  data-plasmic-override={overrides.container12}
                  className={classNames(projectcss.all, sty.container12)}
                />

                <div
                  data-plasmic-name={"container13"}
                  data-plasmic-override={overrides.container13}
                  className={classNames(projectcss.all, sty.container13)}
                />

                <div
                  data-plasmic-name={"container14"}
                  data-plasmic-override={overrides.container14}
                  className={classNames(projectcss.all, sty.container14)}
                />

                <div
                  data-plasmic-name={"container15"}
                  data-plasmic-override={overrides.container15}
                  className={classNames(projectcss.all, sty.container15)}
                />

                <div
                  data-plasmic-name={"container16"}
                  data-plasmic-override={overrides.container16}
                  className={classNames(projectcss.all, sty.container16)}
                />

                <div
                  data-plasmic-name={"container17"}
                  data-plasmic-override={overrides.container17}
                  className={classNames(projectcss.all, sty.container17)}
                />

                <div
                  data-plasmic-name={"container18"}
                  data-plasmic-override={overrides.container18}
                  className={classNames(projectcss.all, sty.container18)}
                />

                <div
                  data-plasmic-name={"container19"}
                  data-plasmic-override={overrides.container19}
                  className={classNames(projectcss.all, sty.container19)}
                />

                <div
                  data-plasmic-name={"container20"}
                  data-plasmic-override={overrides.container20}
                  className={classNames(projectcss.all, sty.container20)}
                />

                <div
                  data-plasmic-name={"container21"}
                  data-plasmic-override={overrides.container21}
                  className={classNames(projectcss.all, sty.container21)}
                />

                <div
                  data-plasmic-name={"container22"}
                  data-plasmic-override={overrides.container22}
                  className={classNames(projectcss.all, sty.container22)}
                />

                <div
                  data-plasmic-name={"container23"}
                  data-plasmic-override={overrides.container23}
                  className={classNames(projectcss.all, sty.container23)}
                />

                <div
                  data-plasmic-name={"container24"}
                  data-plasmic-override={overrides.container24}
                  className={classNames(projectcss.all, sty.container24)}
                />

                <div
                  data-plasmic-name={"container25"}
                  data-plasmic-override={overrides.container25}
                  className={classNames(projectcss.all, sty.container25)}
                />

                <div
                  data-plasmic-name={"container26"}
                  data-plasmic-override={overrides.container26}
                  className={classNames(projectcss.all, sty.container26)}
                />

                <div
                  data-plasmic-name={"container27"}
                  data-plasmic-override={overrides.container27}
                  className={classNames(projectcss.all, sty.container27)}
                />

                <div
                  data-plasmic-name={"container28"}
                  data-plasmic-override={overrides.container28}
                  className={classNames(projectcss.all, sty.container28)}
                />

                <div
                  data-plasmic-name={"container29"}
                  data-plasmic-override={overrides.container29}
                  className={classNames(projectcss.all, sty.container29)}
                />

                <div
                  data-plasmic-name={"container30"}
                  data-plasmic-override={overrides.container30}
                  className={classNames(projectcss.all, sty.container30)}
                />

                <div
                  data-plasmic-name={"container31"}
                  data-plasmic-override={overrides.container31}
                  className={classNames(projectcss.all, sty.container31)}
                />

                <div
                  data-plasmic-name={"container32"}
                  data-plasmic-override={overrides.container32}
                  className={classNames(projectcss.all, sty.container32)}
                />

                <div
                  data-plasmic-name={"container33"}
                  data-plasmic-override={overrides.container33}
                  className={classNames(projectcss.all, sty.container33)}
                />

                <div
                  data-plasmic-name={"container34"}
                  data-plasmic-override={overrides.container34}
                  className={classNames(projectcss.all, sty.container34)}
                />

                <div
                  data-plasmic-name={"container35"}
                  data-plasmic-override={overrides.container35}
                  className={classNames(projectcss.all, sty.container35)}
                />

                <div
                  data-plasmic-name={"container36"}
                  data-plasmic-override={overrides.container36}
                  className={classNames(projectcss.all, sty.container36)}
                />

                <div
                  data-plasmic-name={"container37"}
                  data-plasmic-override={overrides.container37}
                  className={classNames(projectcss.all, sty.container37)}
                />

                <div
                  data-plasmic-name={"container38"}
                  data-plasmic-override={overrides.container38}
                  className={classNames(projectcss.all, sty.container38)}
                />

                <div
                  data-plasmic-name={"container39"}
                  data-plasmic-override={overrides.container39}
                  className={classNames(projectcss.all, sty.container39)}
                />

                <div
                  data-plasmic-name={"container40"}
                  data-plasmic-override={overrides.container40}
                  className={classNames(projectcss.all, sty.container40)}
                />

                <div
                  data-plasmic-name={"container41"}
                  data-plasmic-override={overrides.container41}
                  className={classNames(projectcss.all, sty.container41)}
                />

                <div
                  data-plasmic-name={"container42"}
                  data-plasmic-override={overrides.container42}
                  className={classNames(projectcss.all, sty.container42)}
                />

                <div
                  data-plasmic-name={"container43"}
                  data-plasmic-override={overrides.container43}
                  className={classNames(projectcss.all, sty.container43)}
                />

                <div
                  data-plasmic-name={"container44"}
                  data-plasmic-override={overrides.container44}
                  className={classNames(projectcss.all, sty.container44)}
                />

                <div
                  data-plasmic-name={"container45"}
                  data-plasmic-override={overrides.container45}
                  className={classNames(projectcss.all, sty.container45)}
                />

                <div
                  data-plasmic-name={"container46"}
                  data-plasmic-override={overrides.container46}
                  className={classNames(projectcss.all, sty.container46)}
                />

                <div
                  data-plasmic-name={"container47"}
                  data-plasmic-override={overrides.container47}
                  className={classNames(projectcss.all, sty.container47)}
                />

                <div
                  data-plasmic-name={"container48"}
                  data-plasmic-override={overrides.container48}
                  className={classNames(projectcss.all, sty.container48)}
                />

                <div
                  data-plasmic-name={"container49"}
                  data-plasmic-override={overrides.container49}
                  className={classNames(projectcss.all, sty.container49)}
                />

                <div
                  data-plasmic-name={"container50"}
                  data-plasmic-override={overrides.container50}
                  className={classNames(projectcss.all, sty.container50)}
                />

                <div
                  data-plasmic-name={"container51"}
                  data-plasmic-override={overrides.container51}
                  className={classNames(projectcss.all, sty.container51)}
                />

                <div
                  data-plasmic-name={"container52"}
                  data-plasmic-override={overrides.container52}
                  className={classNames(projectcss.all, sty.container52)}
                />

                <div
                  data-plasmic-name={"container53"}
                  data-plasmic-override={overrides.container53}
                  className={classNames(projectcss.all, sty.container53)}
                />

                <div
                  data-plasmic-name={"container54"}
                  data-plasmic-override={overrides.container54}
                  className={classNames(projectcss.all, sty.container54)}
                />

                <div
                  data-plasmic-name={"container55"}
                  data-plasmic-override={overrides.container55}
                  className={classNames(projectcss.all, sty.container55)}
                />

                <div
                  data-plasmic-name={"container56"}
                  data-plasmic-override={overrides.container56}
                  className={classNames(projectcss.all, sty.container56)}
                />

                <div
                  data-plasmic-name={"container57"}
                  data-plasmic-override={overrides.container57}
                  className={classNames(projectcss.all, sty.container57)}
                />

                <div
                  data-plasmic-name={"container58"}
                  data-plasmic-override={overrides.container58}
                  className={classNames(projectcss.all, sty.container58)}
                />

                <div
                  data-plasmic-name={"container59"}
                  data-plasmic-override={overrides.container59}
                  className={classNames(projectcss.all, sty.container59)}
                />

                <div
                  data-plasmic-name={"container60"}
                  data-plasmic-override={overrides.container60}
                  className={classNames(projectcss.all, sty.container60)}
                />

                <div
                  data-plasmic-name={"container61"}
                  data-plasmic-override={overrides.container61}
                  className={classNames(projectcss.all, sty.container61)}
                />

                <div
                  data-plasmic-name={"container62"}
                  data-plasmic-override={overrides.container62}
                  className={classNames(projectcss.all, sty.container62)}
                />

                <div
                  data-plasmic-name={"container63"}
                  data-plasmic-override={overrides.container63}
                  className={classNames(projectcss.all, sty.container63)}
                />

                <div
                  data-plasmic-name={"container64"}
                  data-plasmic-override={overrides.container64}
                  className={classNames(projectcss.all, sty.container64)}
                />

                <div
                  data-plasmic-name={"container65"}
                  data-plasmic-override={overrides.container65}
                  className={classNames(projectcss.all, sty.container65)}
                />

                <div
                  data-plasmic-name={"container66"}
                  data-plasmic-override={overrides.container66}
                  className={classNames(projectcss.all, sty.container66)}
                />

                <div
                  data-plasmic-name={"container67"}
                  data-plasmic-override={overrides.container67}
                  className={classNames(projectcss.all, sty.container67)}
                />

                <div
                  data-plasmic-name={"container68"}
                  data-plasmic-override={overrides.container68}
                  className={classNames(projectcss.all, sty.container68)}
                />

                <div
                  data-plasmic-name={"container69"}
                  data-plasmic-override={overrides.container69}
                  className={classNames(projectcss.all, sty.container69)}
                />

                <div
                  data-plasmic-name={"container70"}
                  data-plasmic-override={overrides.container70}
                  className={classNames(projectcss.all, sty.container70)}
                />

                <div
                  data-plasmic-name={"container71"}
                  data-plasmic-override={overrides.container71}
                  className={classNames(projectcss.all, sty.container71)}
                />

                <div
                  data-plasmic-name={"container72"}
                  data-plasmic-override={overrides.container72}
                  className={classNames(projectcss.all, sty.container72)}
                />

                <div
                  data-plasmic-name={"container73"}
                  data-plasmic-override={overrides.container73}
                  className={classNames(projectcss.all, sty.container73)}
                />
              </div>
              <div
                data-plasmic-name={"container74"}
                data-plasmic-override={overrides.container74}
                className={classNames(projectcss.all, sty.container74)}
              >
                <div
                  data-plasmic-name={"header"}
                  data-plasmic-override={overrides.header}
                  className={classNames(projectcss.all, sty.header)}
                >
                  <div
                    data-plasmic-name={"link"}
                    data-plasmic-override={overrides.link}
                    className={classNames(projectcss.all, sty.link)}
                  >
                    <div
                      data-plasmic-name={"button"}
                      data-plasmic-override={overrides.button}
                      className={classNames(projectcss.all, sty.button)}
                    >
                      <Icon5Icon
                        className={classNames(projectcss.all, sty.svg__pwMy8)}
                        role={"img"}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__nd7A
                        )}
                      >
                        {"Back"}
                      </div>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"projectPage2"}
                    data-plasmic-override={overrides.projectPage2}
                    className={classNames(projectcss.all, sty.projectPage2)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hKhft
                      )}
                    >
                      {"Erika"}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"container75"}
                  data-plasmic-override={overrides.container75}
                  className={classNames(projectcss.all, sty.container75)}
                >
                  <div
                    data-plasmic-name={"heading1"}
                    data-plasmic-override={overrides.heading1}
                    className={classNames(projectcss.all, sty.heading1)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__bsdOi
                      )}
                    >
                      {"Stage 1 Work"}
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"container76"}
                    data-plasmic-override={overrides.container76}
                    className={classNames(projectcss.all, sty.container76)}
                  >
                    <div
                      data-plasmic-name={"container77"}
                      data-plasmic-override={overrides.container77}
                      className={classNames(projectcss.all, sty.container77)}
                    >
                      <Icon6Icon
                        className={classNames(projectcss.all, sty.svg__d79Cu)}
                        role={"img"}
                      />

                      <div
                        data-plasmic-name={"container78"}
                        data-plasmic-override={overrides.container78}
                        className={classNames(projectcss.all, sty.container78)}
                      >
                        <div
                          data-plasmic-name={"paragraph"}
                          data-plasmic-override={overrides.paragraph}
                          className={classNames(projectcss.all, sty.paragraph)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__lbdJa
                            )}
                          >
                            {"Year"}
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"paragraph2"}
                          data-plasmic-override={overrides.paragraph2}
                          className={classNames(projectcss.all, sty.paragraph2)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___2BfBw
                            )}
                          >
                            {"2023"}
                          </div>
                        </div>
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"container79"}
                      data-plasmic-override={overrides.container79}
                      className={classNames(projectcss.all, sty.container79)}
                    >
                      <PlasmicImg__
                        data-plasmic-name={"img"}
                        data-plasmic-override={overrides.img}
                        alt={""}
                        className={classNames(sty.img)}
                        displayHeight={"18px"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"100%"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"18px"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/minimalist_about_me_page/images/icon7.svg",
                          fullWidth: 18,
                          fullHeight: 18,
                          aspectRatio: undefined
                        }}
                      />

                      <div
                        data-plasmic-name={"container80"}
                        data-plasmic-override={overrides.container80}
                        className={classNames(projectcss.all, sty.container80)}
                      >
                        <div
                          data-plasmic-name={"paragraph3"}
                          data-plasmic-override={overrides.paragraph3}
                          className={classNames(projectcss.all, sty.paragraph3)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___0R1XE
                            )}
                          >
                            {"Type"}
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"paragraph4"}
                          data-plasmic-override={overrides.paragraph4}
                          className={classNames(projectcss.all, sty.paragraph4)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__boZnb
                            )}
                          >
                            {"Academic Project"}
                          </div>
                        </div>
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"container81"}
                      data-plasmic-override={overrides.container81}
                      className={classNames(projectcss.all, sty.container81)}
                    >
                      <Icon8Icon
                        className={classNames(projectcss.all, sty.svg___0ZrjP)}
                        role={"img"}
                      />

                      <div
                        data-plasmic-name={"container82"}
                        data-plasmic-override={overrides.container82}
                        className={classNames(projectcss.all, sty.container82)}
                      >
                        <div
                          data-plasmic-name={"paragraph5"}
                          data-plasmic-override={overrides.paragraph5}
                          className={classNames(projectcss.all, sty.paragraph5)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__c2Ftu
                            )}
                          >
                            {"Location"}
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"paragraph6"}
                          data-plasmic-override={overrides.paragraph6}
                          className={classNames(projectcss.all, sty.paragraph6)}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__mEhQh
                            )}
                          >
                            {"Glasgow School of Art"}
                          </div>
                        </div>
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"container83"}
                      data-plasmic-override={overrides.container83}
                      className={classNames(projectcss.all, sty.container83)}
                    >
                      <div
                        data-plasmic-name={"paragraph7"}
                        data-plasmic-override={overrides.paragraph7}
                        className={classNames(projectcss.all, sty.paragraph7)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__zGf1
                          )}
                        >
                          {"Area"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"paragraph8"}
                        data-plasmic-override={overrides.paragraph8}
                        className={classNames(projectcss.all, sty.paragraph8)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__yYjk
                          )}
                        >
                          {"Various Scales"}
                        </div>
                      </div>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"paragraph9"}
                    data-plasmic-override={overrides.paragraph9}
                    className={classNames(projectcss.all, sty.paragraph9)}
                  >
                    <div
                      data-plasmic-name={
                        "foundationalArchitecturalStudiesExploringSpati"
                      }
                      data-plasmic-override={
                        overrides.foundationalArchitecturalStudiesExploringSpati
                      }
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.foundationalArchitecturalStudiesExploringSpati
                      )}
                    >
                      {
                        "Foundational architectural studies exploring spatial relationships, form, and materiality. This collection represents early explorations in design thinking and architectural representation."
                      }
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"container84"}
                  data-plasmic-override={overrides.container84}
                  className={classNames(projectcss.all, sty.container84)}
                >
                  <div
                    data-plasmic-name={"container85"}
                    data-plasmic-override={overrides.container85}
                    className={classNames(projectcss.all, sty.container85)}
                  >
                    <div
                      data-plasmic-name={"projectPage3"}
                      data-plasmic-override={overrides.projectPage3}
                      className={classNames(projectcss.all, sty.projectPage3)}
                    />
                  </div>
                  <div
                    data-plasmic-name={"container86"}
                    data-plasmic-override={overrides.container86}
                    className={classNames(projectcss.all, sty.container86)}
                  >
                    <div
                      data-plasmic-name={"projectPage4"}
                      data-plasmic-override={overrides.projectPage4}
                      className={classNames(projectcss.all, sty.projectPage4)}
                    />
                  </div>
                  <div
                    data-plasmic-name={"container87"}
                    data-plasmic-override={overrides.container87}
                    className={classNames(projectcss.all, sty.container87)}
                  >
                    <div
                      data-plasmic-name={"projectPage5"}
                      data-plasmic-override={overrides.projectPage5}
                      className={classNames(projectcss.all, sty.projectPage5)}
                    />
                  </div>
                  <div
                    data-plasmic-name={"container88"}
                    data-plasmic-override={overrides.container88}
                    className={classNames(projectcss.all, sty.container88)}
                  >
                    <div
                      data-plasmic-name={"projectPage6"}
                      data-plasmic-override={overrides.projectPage6}
                      className={classNames(projectcss.all, sty.projectPage6)}
                    />
                  </div>
                  <div
                    data-plasmic-name={"container89"}
                    data-plasmic-override={overrides.container89}
                    className={classNames(projectcss.all, sty.container89)}
                  >
                    <div
                      data-plasmic-name={"projectPage7"}
                      data-plasmic-override={overrides.projectPage7}
                      className={classNames(projectcss.all, sty.projectPage7)}
                    />
                  </div>
                  <div
                    data-plasmic-name={"container90"}
                    data-plasmic-override={overrides.container90}
                    className={classNames(projectcss.all, sty.container90)}
                  >
                    <div
                      data-plasmic-name={"projectPage8"}
                      data-plasmic-override={overrides.projectPage8}
                      className={classNames(projectcss.all, sty.projectPage8)}
                    />
                  </div>
                </div>
                <div
                  data-plasmic-name={"container91"}
                  data-plasmic-override={overrides.container91}
                  className={classNames(projectcss.all, sty.container91)}
                >
                  <div
                    data-plasmic-name={"container92"}
                    data-plasmic-override={overrides.container92}
                    className={classNames(projectcss.all, sty.container92)}
                  >
                    <div
                      data-plasmic-name={"heading3"}
                      data-plasmic-override={overrides.heading3}
                      className={classNames(projectcss.all, sty.heading3)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__vrXmd
                        )}
                      >
                        {"Key Concepts"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"container93"}
                      data-plasmic-override={overrides.container93}
                      className={classNames(projectcss.all, sty.container93)}
                    >
                      <div
                        data-plasmic-name={"text"}
                        data-plasmic-override={overrides.text}
                        className={classNames(projectcss.all, sty.text)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___1N5Lv
                          )}
                        >
                          {"Form and Space"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"text2"}
                        data-plasmic-override={overrides.text2}
                        className={classNames(projectcss.all, sty.text2)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__nAwK
                          )}
                        >
                          {"Material Expression"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"text3"}
                        data-plasmic-override={overrides.text3}
                        className={classNames(projectcss.all, sty.text3)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__umOqi
                          )}
                        >
                          {"Light and Shadow"}
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"text4"}
                        data-plasmic-override={overrides.text4}
                        className={classNames(projectcss.all, sty.text4)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__wRzN9
                          )}
                        >
                          {"Human Scale"}
                        </div>
                      </div>
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"container94"}
                    data-plasmic-override={overrides.container94}
                    className={classNames(projectcss.all, sty.container94)}
                  >
                    <div
                      data-plasmic-name={"heading4"}
                      data-plasmic-override={overrides.heading4}
                      className={classNames(projectcss.all, sty.heading4)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__zUtlm
                        )}
                      >
                        {"Project Details"}
                      </div>
                    </div>
                    <div
                      data-plasmic-name={"list"}
                      data-plasmic-override={overrides.list}
                      className={classNames(projectcss.all, sty.list)}
                    >
                      <div
                        data-plasmic-name={"listItem"}
                        data-plasmic-override={overrides.listItem}
                        className={classNames(projectcss.all, sty.listItem)}
                      >
                        <div
                          data-plasmic-name={"projectPage9"}
                          data-plasmic-override={overrides.projectPage9}
                          className={classNames(
                            projectcss.all,
                            sty.projectPage9
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___2KFOj
                            )}
                          >
                            {"\u2022"}
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"projectPage10"}
                          data-plasmic-override={overrides.projectPage10}
                          className={classNames(
                            projectcss.all,
                            sty.projectPage10
                          )}
                        >
                          <div
                            data-plasmic-name={
                              "explorationOfBasicSpatialConceptsAndArchitec"
                            }
                            data-plasmic-override={
                              overrides.explorationOfBasicSpatialConceptsAndArchitec
                            }
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.explorationOfBasicSpatialConceptsAndArchitec
                            )}
                          >
                            {
                              "Exploration of basic spatial concepts and architectural elements"
                            }
                          </div>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"listItem2"}
                        data-plasmic-override={overrides.listItem2}
                        className={classNames(projectcss.all, sty.listItem2)}
                      >
                        <div
                          data-plasmic-name={"projectPage11"}
                          data-plasmic-override={overrides.projectPage11}
                          className={classNames(
                            projectcss.all,
                            sty.projectPage11
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__hng4I
                            )}
                          >
                            {"\u2022"}
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"projectPage12"}
                          data-plasmic-override={overrides.projectPage12}
                          className={classNames(
                            projectcss.all,
                            sty.projectPage12
                          )}
                        >
                          <div
                            data-plasmic-name={
                              "studyOfProportionScaleAndHumanExperienceI"
                            }
                            data-plasmic-override={
                              overrides.studyOfProportionScaleAndHumanExperienceI
                            }
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.studyOfProportionScaleAndHumanExperienceI
                            )}
                          >
                            {
                              "Study of proportion, scale, and human experience in space"
                            }
                          </div>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"listItem3"}
                        data-plasmic-override={overrides.listItem3}
                        className={classNames(projectcss.all, sty.listItem3)}
                      >
                        <div
                          data-plasmic-name={"projectPage13"}
                          data-plasmic-override={overrides.projectPage13}
                          className={classNames(
                            projectcss.all,
                            sty.projectPage13
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ctLGy
                            )}
                          >
                            {"\u2022"}
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"projectPage14"}
                          data-plasmic-override={overrides.projectPage14}
                          className={classNames(
                            projectcss.all,
                            sty.projectPage14
                          )}
                        >
                          <div
                            data-plasmic-name={
                              "developmentOfRepresentationTechniquesAndDesig"
                            }
                            data-plasmic-override={
                              overrides.developmentOfRepresentationTechniquesAndDesig
                            }
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.developmentOfRepresentationTechniquesAndDesig
                            )}
                          >
                            {
                              "Development of representation techniques and design methodologies"
                            }
                          </div>
                        </div>
                      </div>
                      <div
                        data-plasmic-name={"listItem4"}
                        data-plasmic-override={overrides.listItem4}
                        className={classNames(projectcss.all, sty.listItem4)}
                      >
                        <div
                          data-plasmic-name={"projectPage15"}
                          data-plasmic-override={overrides.projectPage15}
                          className={classNames(
                            projectcss.all,
                            sty.projectPage15
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__muo1F
                            )}
                          >
                            {"\u2022"}
                          </div>
                        </div>
                        <div
                          data-plasmic-name={"projectPage16"}
                          data-plasmic-override={overrides.projectPage16}
                          className={classNames(
                            projectcss.all,
                            sty.projectPage16
                          )}
                        >
                          <div
                            data-plasmic-name={
                              "focusOnUnderstandingMaterialityAndConstructio"
                            }
                            data-plasmic-override={
                              overrides.focusOnUnderstandingMaterialityAndConstructio
                            }
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.focusOnUnderstandingMaterialityAndConstructio
                            )}
                          >
                            {
                              "Focus on understanding materiality and construction principles"
                            }
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "animatedPortfolioWebsite",
    "projectPage",
    "container",
    "container2",
    "container3",
    "container4",
    "container5",
    "container6",
    "container7",
    "container8",
    "container9",
    "container10",
    "container11",
    "container12",
    "container13",
    "container14",
    "container15",
    "container16",
    "container17",
    "container18",
    "container19",
    "container20",
    "container21",
    "container22",
    "container23",
    "container24",
    "container25",
    "container26",
    "container27",
    "container28",
    "container29",
    "container30",
    "container31",
    "container32",
    "container33",
    "container34",
    "container35",
    "container36",
    "container37",
    "container38",
    "container39",
    "container40",
    "container41",
    "container42",
    "container43",
    "container44",
    "container45",
    "container46",
    "container47",
    "container48",
    "container49",
    "container50",
    "container51",
    "container52",
    "container53",
    "container54",
    "container55",
    "container56",
    "container57",
    "container58",
    "container59",
    "container60",
    "container61",
    "container62",
    "container63",
    "container64",
    "container65",
    "container66",
    "container67",
    "container68",
    "container69",
    "container70",
    "container71",
    "container72",
    "container73",
    "container74",
    "header",
    "link",
    "button",
    "projectPage2",
    "container75",
    "heading1",
    "container76",
    "container77",
    "container78",
    "paragraph",
    "paragraph2",
    "container79",
    "img",
    "container80",
    "paragraph3",
    "paragraph4",
    "container81",
    "container82",
    "paragraph5",
    "paragraph6",
    "container83",
    "paragraph7",
    "paragraph8",
    "paragraph9",
    "foundationalArchitecturalStudiesExploringSpati",
    "container84",
    "container85",
    "projectPage3",
    "container86",
    "projectPage4",
    "container87",
    "projectPage5",
    "container88",
    "projectPage6",
    "container89",
    "projectPage7",
    "container90",
    "projectPage8",
    "container91",
    "container92",
    "heading3",
    "container93",
    "text",
    "text2",
    "text3",
    "text4",
    "container94",
    "heading4",
    "list",
    "listItem",
    "projectPage9",
    "projectPage10",
    "explorationOfBasicSpatialConceptsAndArchitec",
    "listItem2",
    "projectPage11",
    "projectPage12",
    "studyOfProportionScaleAndHumanExperienceI",
    "listItem3",
    "projectPage13",
    "projectPage14",
    "developmentOfRepresentationTechniquesAndDesig",
    "listItem4",
    "projectPage15",
    "projectPage16",
    "focusOnUnderstandingMaterialityAndConstructio"
  ],
  animatedPortfolioWebsite: [
    "animatedPortfolioWebsite",
    "projectPage",
    "container",
    "container2",
    "container3",
    "container4",
    "container5",
    "container6",
    "container7",
    "container8",
    "container9",
    "container10",
    "container11",
    "container12",
    "container13",
    "container14",
    "container15",
    "container16",
    "container17",
    "container18",
    "container19",
    "container20",
    "container21",
    "container22",
    "container23",
    "container24",
    "container25",
    "container26",
    "container27",
    "container28",
    "container29",
    "container30",
    "container31",
    "container32",
    "container33",
    "container34",
    "container35",
    "container36",
    "container37",
    "container38",
    "container39",
    "container40",
    "container41",
    "container42",
    "container43",
    "container44",
    "container45",
    "container46",
    "container47",
    "container48",
    "container49",
    "container50",
    "container51",
    "container52",
    "container53",
    "container54",
    "container55",
    "container56",
    "container57",
    "container58",
    "container59",
    "container60",
    "container61",
    "container62",
    "container63",
    "container64",
    "container65",
    "container66",
    "container67",
    "container68",
    "container69",
    "container70",
    "container71",
    "container72",
    "container73",
    "container74",
    "header",
    "link",
    "button",
    "projectPage2",
    "container75",
    "heading1",
    "container76",
    "container77",
    "container78",
    "paragraph",
    "paragraph2",
    "container79",
    "img",
    "container80",
    "paragraph3",
    "paragraph4",
    "container81",
    "container82",
    "paragraph5",
    "paragraph6",
    "container83",
    "paragraph7",
    "paragraph8",
    "paragraph9",
    "foundationalArchitecturalStudiesExploringSpati",
    "container84",
    "container85",
    "projectPage3",
    "container86",
    "projectPage4",
    "container87",
    "projectPage5",
    "container88",
    "projectPage6",
    "container89",
    "projectPage7",
    "container90",
    "projectPage8",
    "container91",
    "container92",
    "heading3",
    "container93",
    "text",
    "text2",
    "text3",
    "text4",
    "container94",
    "heading4",
    "list",
    "listItem",
    "projectPage9",
    "projectPage10",
    "explorationOfBasicSpatialConceptsAndArchitec",
    "listItem2",
    "projectPage11",
    "projectPage12",
    "studyOfProportionScaleAndHumanExperienceI",
    "listItem3",
    "projectPage13",
    "projectPage14",
    "developmentOfRepresentationTechniquesAndDesig",
    "listItem4",
    "projectPage15",
    "projectPage16",
    "focusOnUnderstandingMaterialityAndConstructio"
  ],
  projectPage: [
    "projectPage",
    "container",
    "container2",
    "container3",
    "container4",
    "container5",
    "container6",
    "container7",
    "container8",
    "container9",
    "container10",
    "container11",
    "container12",
    "container13",
    "container14",
    "container15",
    "container16",
    "container17",
    "container18",
    "container19",
    "container20",
    "container21",
    "container22",
    "container23",
    "container24",
    "container25",
    "container26",
    "container27",
    "container28",
    "container29",
    "container30",
    "container31",
    "container32",
    "container33",
    "container34",
    "container35",
    "container36",
    "container37",
    "container38",
    "container39",
    "container40",
    "container41",
    "container42",
    "container43",
    "container44",
    "container45",
    "container46",
    "container47",
    "container48",
    "container49",
    "container50",
    "container51",
    "container52",
    "container53",
    "container54",
    "container55",
    "container56",
    "container57",
    "container58",
    "container59",
    "container60",
    "container61",
    "container62",
    "container63",
    "container64",
    "container65",
    "container66",
    "container67",
    "container68",
    "container69",
    "container70",
    "container71",
    "container72",
    "container73",
    "container74",
    "header",
    "link",
    "button",
    "projectPage2",
    "container75",
    "heading1",
    "container76",
    "container77",
    "container78",
    "paragraph",
    "paragraph2",
    "container79",
    "img",
    "container80",
    "paragraph3",
    "paragraph4",
    "container81",
    "container82",
    "paragraph5",
    "paragraph6",
    "container83",
    "paragraph7",
    "paragraph8",
    "paragraph9",
    "foundationalArchitecturalStudiesExploringSpati",
    "container84",
    "container85",
    "projectPage3",
    "container86",
    "projectPage4",
    "container87",
    "projectPage5",
    "container88",
    "projectPage6",
    "container89",
    "projectPage7",
    "container90",
    "projectPage8",
    "container91",
    "container92",
    "heading3",
    "container93",
    "text",
    "text2",
    "text3",
    "text4",
    "container94",
    "heading4",
    "list",
    "listItem",
    "projectPage9",
    "projectPage10",
    "explorationOfBasicSpatialConceptsAndArchitec",
    "listItem2",
    "projectPage11",
    "projectPage12",
    "studyOfProportionScaleAndHumanExperienceI",
    "listItem3",
    "projectPage13",
    "projectPage14",
    "developmentOfRepresentationTechniquesAndDesig",
    "listItem4",
    "projectPage15",
    "projectPage16",
    "focusOnUnderstandingMaterialityAndConstructio"
  ],
  container: [
    "container",
    "container2",
    "container3",
    "container4",
    "container5",
    "container6",
    "container7",
    "container8",
    "container9",
    "container10",
    "container11",
    "container12",
    "container13",
    "container14",
    "container15",
    "container16",
    "container17",
    "container18",
    "container19",
    "container20",
    "container21",
    "container22",
    "container23",
    "container24",
    "container25",
    "container26",
    "container27",
    "container28",
    "container29",
    "container30",
    "container31",
    "container32",
    "container33",
    "container34",
    "container35",
    "container36",
    "container37",
    "container38",
    "container39",
    "container40",
    "container41",
    "container42",
    "container43",
    "container44",
    "container45",
    "container46",
    "container47",
    "container48",
    "container49",
    "container50",
    "container51",
    "container52",
    "container53",
    "container54",
    "container55",
    "container56",
    "container57",
    "container58",
    "container59",
    "container60",
    "container61",
    "container62",
    "container63",
    "container64",
    "container65",
    "container66",
    "container67",
    "container68",
    "container69",
    "container70",
    "container71",
    "container72",
    "container73"
  ],
  container2: ["container2"],
  container3: ["container3"],
  container4: ["container4"],
  container5: ["container5"],
  container6: ["container6"],
  container7: ["container7"],
  container8: ["container8"],
  container9: ["container9"],
  container10: ["container10"],
  container11: ["container11"],
  container12: ["container12"],
  container13: ["container13"],
  container14: ["container14"],
  container15: ["container15"],
  container16: ["container16"],
  container17: ["container17"],
  container18: ["container18"],
  container19: ["container19"],
  container20: ["container20"],
  container21: ["container21"],
  container22: ["container22"],
  container23: ["container23"],
  container24: ["container24"],
  container25: ["container25"],
  container26: ["container26"],
  container27: ["container27"],
  container28: ["container28"],
  container29: ["container29"],
  container30: ["container30"],
  container31: ["container31"],
  container32: ["container32"],
  container33: ["container33"],
  container34: ["container34"],
  container35: ["container35"],
  container36: ["container36"],
  container37: ["container37"],
  container38: ["container38"],
  container39: ["container39"],
  container40: ["container40"],
  container41: ["container41"],
  container42: ["container42"],
  container43: ["container43"],
  container44: ["container44"],
  container45: ["container45"],
  container46: ["container46"],
  container47: ["container47"],
  container48: ["container48"],
  container49: ["container49"],
  container50: ["container50"],
  container51: ["container51"],
  container52: ["container52"],
  container53: ["container53"],
  container54: ["container54"],
  container55: ["container55"],
  container56: ["container56"],
  container57: ["container57"],
  container58: ["container58"],
  container59: ["container59"],
  container60: ["container60"],
  container61: ["container61"],
  container62: ["container62"],
  container63: ["container63"],
  container64: ["container64"],
  container65: ["container65"],
  container66: ["container66"],
  container67: ["container67"],
  container68: ["container68"],
  container69: ["container69"],
  container70: ["container70"],
  container71: ["container71"],
  container72: ["container72"],
  container73: ["container73"],
  container74: [
    "container74",
    "header",
    "link",
    "button",
    "projectPage2",
    "container75",
    "heading1",
    "container76",
    "container77",
    "container78",
    "paragraph",
    "paragraph2",
    "container79",
    "img",
    "container80",
    "paragraph3",
    "paragraph4",
    "container81",
    "container82",
    "paragraph5",
    "paragraph6",
    "container83",
    "paragraph7",
    "paragraph8",
    "paragraph9",
    "foundationalArchitecturalStudiesExploringSpati",
    "container84",
    "container85",
    "projectPage3",
    "container86",
    "projectPage4",
    "container87",
    "projectPage5",
    "container88",
    "projectPage6",
    "container89",
    "projectPage7",
    "container90",
    "projectPage8",
    "container91",
    "container92",
    "heading3",
    "container93",
    "text",
    "text2",
    "text3",
    "text4",
    "container94",
    "heading4",
    "list",
    "listItem",
    "projectPage9",
    "projectPage10",
    "explorationOfBasicSpatialConceptsAndArchitec",
    "listItem2",
    "projectPage11",
    "projectPage12",
    "studyOfProportionScaleAndHumanExperienceI",
    "listItem3",
    "projectPage13",
    "projectPage14",
    "developmentOfRepresentationTechniquesAndDesig",
    "listItem4",
    "projectPage15",
    "projectPage16",
    "focusOnUnderstandingMaterialityAndConstructio"
  ],
  header: ["header", "link", "button", "projectPage2"],
  link: ["link", "button"],
  button: ["button"],
  projectPage2: ["projectPage2"],
  container75: [
    "container75",
    "heading1",
    "container76",
    "container77",
    "container78",
    "paragraph",
    "paragraph2",
    "container79",
    "img",
    "container80",
    "paragraph3",
    "paragraph4",
    "container81",
    "container82",
    "paragraph5",
    "paragraph6",
    "container83",
    "paragraph7",
    "paragraph8",
    "paragraph9",
    "foundationalArchitecturalStudiesExploringSpati"
  ],
  heading1: ["heading1"],
  container76: [
    "container76",
    "container77",
    "container78",
    "paragraph",
    "paragraph2",
    "container79",
    "img",
    "container80",
    "paragraph3",
    "paragraph4",
    "container81",
    "container82",
    "paragraph5",
    "paragraph6",
    "container83",
    "paragraph7",
    "paragraph8"
  ],
  container77: ["container77", "container78", "paragraph", "paragraph2"],
  container78: ["container78", "paragraph", "paragraph2"],
  paragraph: ["paragraph"],
  paragraph2: ["paragraph2"],
  container79: [
    "container79",
    "img",
    "container80",
    "paragraph3",
    "paragraph4"
  ],
  img: ["img"],
  container80: ["container80", "paragraph3", "paragraph4"],
  paragraph3: ["paragraph3"],
  paragraph4: ["paragraph4"],
  container81: ["container81", "container82", "paragraph5", "paragraph6"],
  container82: ["container82", "paragraph5", "paragraph6"],
  paragraph5: ["paragraph5"],
  paragraph6: ["paragraph6"],
  container83: ["container83", "paragraph7", "paragraph8"],
  paragraph7: ["paragraph7"],
  paragraph8: ["paragraph8"],
  paragraph9: ["paragraph9", "foundationalArchitecturalStudiesExploringSpati"],
  foundationalArchitecturalStudiesExploringSpati: [
    "foundationalArchitecturalStudiesExploringSpati"
  ],
  container84: [
    "container84",
    "container85",
    "projectPage3",
    "container86",
    "projectPage4",
    "container87",
    "projectPage5",
    "container88",
    "projectPage6",
    "container89",
    "projectPage7",
    "container90",
    "projectPage8"
  ],
  container85: ["container85", "projectPage3"],
  projectPage3: ["projectPage3"],
  container86: ["container86", "projectPage4"],
  projectPage4: ["projectPage4"],
  container87: ["container87", "projectPage5"],
  projectPage5: ["projectPage5"],
  container88: ["container88", "projectPage6"],
  projectPage6: ["projectPage6"],
  container89: ["container89", "projectPage7"],
  projectPage7: ["projectPage7"],
  container90: ["container90", "projectPage8"],
  projectPage8: ["projectPage8"],
  container91: [
    "container91",
    "container92",
    "heading3",
    "container93",
    "text",
    "text2",
    "text3",
    "text4",
    "container94",
    "heading4",
    "list",
    "listItem",
    "projectPage9",
    "projectPage10",
    "explorationOfBasicSpatialConceptsAndArchitec",
    "listItem2",
    "projectPage11",
    "projectPage12",
    "studyOfProportionScaleAndHumanExperienceI",
    "listItem3",
    "projectPage13",
    "projectPage14",
    "developmentOfRepresentationTechniquesAndDesig",
    "listItem4",
    "projectPage15",
    "projectPage16",
    "focusOnUnderstandingMaterialityAndConstructio"
  ],
  container92: [
    "container92",
    "heading3",
    "container93",
    "text",
    "text2",
    "text3",
    "text4"
  ],
  heading3: ["heading3"],
  container93: ["container93", "text", "text2", "text3", "text4"],
  text: ["text"],
  text2: ["text2"],
  text3: ["text3"],
  text4: ["text4"],
  container94: [
    "container94",
    "heading4",
    "list",
    "listItem",
    "projectPage9",
    "projectPage10",
    "explorationOfBasicSpatialConceptsAndArchitec",
    "listItem2",
    "projectPage11",
    "projectPage12",
    "studyOfProportionScaleAndHumanExperienceI",
    "listItem3",
    "projectPage13",
    "projectPage14",
    "developmentOfRepresentationTechniquesAndDesig",
    "listItem4",
    "projectPage15",
    "projectPage16",
    "focusOnUnderstandingMaterialityAndConstructio"
  ],
  heading4: ["heading4"],
  list: [
    "list",
    "listItem",
    "projectPage9",
    "projectPage10",
    "explorationOfBasicSpatialConceptsAndArchitec",
    "listItem2",
    "projectPage11",
    "projectPage12",
    "studyOfProportionScaleAndHumanExperienceI",
    "listItem3",
    "projectPage13",
    "projectPage14",
    "developmentOfRepresentationTechniquesAndDesig",
    "listItem4",
    "projectPage15",
    "projectPage16",
    "focusOnUnderstandingMaterialityAndConstructio"
  ],
  listItem: [
    "listItem",
    "projectPage9",
    "projectPage10",
    "explorationOfBasicSpatialConceptsAndArchitec"
  ],
  projectPage9: ["projectPage9"],
  projectPage10: [
    "projectPage10",
    "explorationOfBasicSpatialConceptsAndArchitec"
  ],
  explorationOfBasicSpatialConceptsAndArchitec: [
    "explorationOfBasicSpatialConceptsAndArchitec"
  ],
  listItem2: [
    "listItem2",
    "projectPage11",
    "projectPage12",
    "studyOfProportionScaleAndHumanExperienceI"
  ],
  projectPage11: ["projectPage11"],
  projectPage12: ["projectPage12", "studyOfProportionScaleAndHumanExperienceI"],
  studyOfProportionScaleAndHumanExperienceI: [
    "studyOfProportionScaleAndHumanExperienceI"
  ],
  listItem3: [
    "listItem3",
    "projectPage13",
    "projectPage14",
    "developmentOfRepresentationTechniquesAndDesig"
  ],
  projectPage13: ["projectPage13"],
  projectPage14: [
    "projectPage14",
    "developmentOfRepresentationTechniquesAndDesig"
  ],
  developmentOfRepresentationTechniquesAndDesig: [
    "developmentOfRepresentationTechniquesAndDesig"
  ],
  listItem4: [
    "listItem4",
    "projectPage15",
    "projectPage16",
    "focusOnUnderstandingMaterialityAndConstructio"
  ],
  projectPage15: ["projectPage15"],
  projectPage16: [
    "projectPage16",
    "focusOnUnderstandingMaterialityAndConstructio"
  ],
  focusOnUnderstandingMaterialityAndConstructio: [
    "focusOnUnderstandingMaterialityAndConstructio"
  ]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  animatedPortfolioWebsite: "div";
  projectPage: "div";
  container: "div";
  container2: "div";
  container3: "div";
  container4: "div";
  container5: "div";
  container6: "div";
  container7: "div";
  container8: "div";
  container9: "div";
  container10: "div";
  container11: "div";
  container12: "div";
  container13: "div";
  container14: "div";
  container15: "div";
  container16: "div";
  container17: "div";
  container18: "div";
  container19: "div";
  container20: "div";
  container21: "div";
  container22: "div";
  container23: "div";
  container24: "div";
  container25: "div";
  container26: "div";
  container27: "div";
  container28: "div";
  container29: "div";
  container30: "div";
  container31: "div";
  container32: "div";
  container33: "div";
  container34: "div";
  container35: "div";
  container36: "div";
  container37: "div";
  container38: "div";
  container39: "div";
  container40: "div";
  container41: "div";
  container42: "div";
  container43: "div";
  container44: "div";
  container45: "div";
  container46: "div";
  container47: "div";
  container48: "div";
  container49: "div";
  container50: "div";
  container51: "div";
  container52: "div";
  container53: "div";
  container54: "div";
  container55: "div";
  container56: "div";
  container57: "div";
  container58: "div";
  container59: "div";
  container60: "div";
  container61: "div";
  container62: "div";
  container63: "div";
  container64: "div";
  container65: "div";
  container66: "div";
  container67: "div";
  container68: "div";
  container69: "div";
  container70: "div";
  container71: "div";
  container72: "div";
  container73: "div";
  container74: "div";
  header: "div";
  link: "div";
  button: "div";
  projectPage2: "div";
  container75: "div";
  heading1: "div";
  container76: "div";
  container77: "div";
  container78: "div";
  paragraph: "div";
  paragraph2: "div";
  container79: "div";
  img: typeof PlasmicImg__;
  container80: "div";
  paragraph3: "div";
  paragraph4: "div";
  container81: "div";
  container82: "div";
  paragraph5: "div";
  paragraph6: "div";
  container83: "div";
  paragraph7: "div";
  paragraph8: "div";
  paragraph9: "div";
  foundationalArchitecturalStudiesExploringSpati: "div";
  container84: "div";
  container85: "div";
  projectPage3: "div";
  container86: "div";
  projectPage4: "div";
  container87: "div";
  projectPage5: "div";
  container88: "div";
  projectPage6: "div";
  container89: "div";
  projectPage7: "div";
  container90: "div";
  projectPage8: "div";
  container91: "div";
  container92: "div";
  heading3: "div";
  container93: "div";
  text: "div";
  text2: "div";
  text3: "div";
  text4: "div";
  container94: "div";
  heading4: "div";
  list: "div";
  listItem: "div";
  projectPage9: "div";
  projectPage10: "div";
  explorationOfBasicSpatialConceptsAndArchitec: "div";
  listItem2: "div";
  projectPage11: "div";
  projectPage12: "div";
  studyOfProportionScaleAndHumanExperienceI: "div";
  listItem3: "div";
  projectPage13: "div";
  projectPage14: "div";
  developmentOfRepresentationTechniquesAndDesig: "div";
  listItem4: "div";
  projectPage15: "div";
  projectPage16: "div";
  focusOnUnderstandingMaterialityAndConstructio: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNewPage2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNewPage2__VariantsArgs;
    args?: PlasmicNewPage2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicNewPage2__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicNewPage2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicNewPage2__ArgProps,
          internalVariantPropNames: PlasmicNewPage2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNewPage2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNewPage2";
  } else {
    func.displayName = `PlasmicNewPage2.${nodeName}`;
  }
  return func;
}

export const PlasmicNewPage2 = Object.assign(
  // Top-level PlasmicNewPage2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    animatedPortfolioWebsite: makeNodeComponent("animatedPortfolioWebsite"),
    projectPage: makeNodeComponent("projectPage"),
    container: makeNodeComponent("container"),
    container2: makeNodeComponent("container2"),
    container3: makeNodeComponent("container3"),
    container4: makeNodeComponent("container4"),
    container5: makeNodeComponent("container5"),
    container6: makeNodeComponent("container6"),
    container7: makeNodeComponent("container7"),
    container8: makeNodeComponent("container8"),
    container9: makeNodeComponent("container9"),
    container10: makeNodeComponent("container10"),
    container11: makeNodeComponent("container11"),
    container12: makeNodeComponent("container12"),
    container13: makeNodeComponent("container13"),
    container14: makeNodeComponent("container14"),
    container15: makeNodeComponent("container15"),
    container16: makeNodeComponent("container16"),
    container17: makeNodeComponent("container17"),
    container18: makeNodeComponent("container18"),
    container19: makeNodeComponent("container19"),
    container20: makeNodeComponent("container20"),
    container21: makeNodeComponent("container21"),
    container22: makeNodeComponent("container22"),
    container23: makeNodeComponent("container23"),
    container24: makeNodeComponent("container24"),
    container25: makeNodeComponent("container25"),
    container26: makeNodeComponent("container26"),
    container27: makeNodeComponent("container27"),
    container28: makeNodeComponent("container28"),
    container29: makeNodeComponent("container29"),
    container30: makeNodeComponent("container30"),
    container31: makeNodeComponent("container31"),
    container32: makeNodeComponent("container32"),
    container33: makeNodeComponent("container33"),
    container34: makeNodeComponent("container34"),
    container35: makeNodeComponent("container35"),
    container36: makeNodeComponent("container36"),
    container37: makeNodeComponent("container37"),
    container38: makeNodeComponent("container38"),
    container39: makeNodeComponent("container39"),
    container40: makeNodeComponent("container40"),
    container41: makeNodeComponent("container41"),
    container42: makeNodeComponent("container42"),
    container43: makeNodeComponent("container43"),
    container44: makeNodeComponent("container44"),
    container45: makeNodeComponent("container45"),
    container46: makeNodeComponent("container46"),
    container47: makeNodeComponent("container47"),
    container48: makeNodeComponent("container48"),
    container49: makeNodeComponent("container49"),
    container50: makeNodeComponent("container50"),
    container51: makeNodeComponent("container51"),
    container52: makeNodeComponent("container52"),
    container53: makeNodeComponent("container53"),
    container54: makeNodeComponent("container54"),
    container55: makeNodeComponent("container55"),
    container56: makeNodeComponent("container56"),
    container57: makeNodeComponent("container57"),
    container58: makeNodeComponent("container58"),
    container59: makeNodeComponent("container59"),
    container60: makeNodeComponent("container60"),
    container61: makeNodeComponent("container61"),
    container62: makeNodeComponent("container62"),
    container63: makeNodeComponent("container63"),
    container64: makeNodeComponent("container64"),
    container65: makeNodeComponent("container65"),
    container66: makeNodeComponent("container66"),
    container67: makeNodeComponent("container67"),
    container68: makeNodeComponent("container68"),
    container69: makeNodeComponent("container69"),
    container70: makeNodeComponent("container70"),
    container71: makeNodeComponent("container71"),
    container72: makeNodeComponent("container72"),
    container73: makeNodeComponent("container73"),
    container74: makeNodeComponent("container74"),
    header: makeNodeComponent("header"),
    link: makeNodeComponent("link"),
    button: makeNodeComponent("button"),
    projectPage2: makeNodeComponent("projectPage2"),
    container75: makeNodeComponent("container75"),
    heading1: makeNodeComponent("heading1"),
    container76: makeNodeComponent("container76"),
    container77: makeNodeComponent("container77"),
    container78: makeNodeComponent("container78"),
    paragraph: makeNodeComponent("paragraph"),
    paragraph2: makeNodeComponent("paragraph2"),
    container79: makeNodeComponent("container79"),
    img: makeNodeComponent("img"),
    container80: makeNodeComponent("container80"),
    paragraph3: makeNodeComponent("paragraph3"),
    paragraph4: makeNodeComponent("paragraph4"),
    container81: makeNodeComponent("container81"),
    container82: makeNodeComponent("container82"),
    paragraph5: makeNodeComponent("paragraph5"),
    paragraph6: makeNodeComponent("paragraph6"),
    container83: makeNodeComponent("container83"),
    paragraph7: makeNodeComponent("paragraph7"),
    paragraph8: makeNodeComponent("paragraph8"),
    paragraph9: makeNodeComponent("paragraph9"),
    foundationalArchitecturalStudiesExploringSpati: makeNodeComponent(
      "foundationalArchitecturalStudiesExploringSpati"
    ),
    container84: makeNodeComponent("container84"),
    container85: makeNodeComponent("container85"),
    projectPage3: makeNodeComponent("projectPage3"),
    container86: makeNodeComponent("container86"),
    projectPage4: makeNodeComponent("projectPage4"),
    container87: makeNodeComponent("container87"),
    projectPage5: makeNodeComponent("projectPage5"),
    container88: makeNodeComponent("container88"),
    projectPage6: makeNodeComponent("projectPage6"),
    container89: makeNodeComponent("container89"),
    projectPage7: makeNodeComponent("projectPage7"),
    container90: makeNodeComponent("container90"),
    projectPage8: makeNodeComponent("projectPage8"),
    container91: makeNodeComponent("container91"),
    container92: makeNodeComponent("container92"),
    heading3: makeNodeComponent("heading3"),
    container93: makeNodeComponent("container93"),
    text: makeNodeComponent("text"),
    text2: makeNodeComponent("text2"),
    text3: makeNodeComponent("text3"),
    text4: makeNodeComponent("text4"),
    container94: makeNodeComponent("container94"),
    heading4: makeNodeComponent("heading4"),
    list: makeNodeComponent("list"),
    listItem: makeNodeComponent("listItem"),
    projectPage9: makeNodeComponent("projectPage9"),
    projectPage10: makeNodeComponent("projectPage10"),
    explorationOfBasicSpatialConceptsAndArchitec: makeNodeComponent(
      "explorationOfBasicSpatialConceptsAndArchitec"
    ),
    listItem2: makeNodeComponent("listItem2"),
    projectPage11: makeNodeComponent("projectPage11"),
    projectPage12: makeNodeComponent("projectPage12"),
    studyOfProportionScaleAndHumanExperienceI: makeNodeComponent(
      "studyOfProportionScaleAndHumanExperienceI"
    ),
    listItem3: makeNodeComponent("listItem3"),
    projectPage13: makeNodeComponent("projectPage13"),
    projectPage14: makeNodeComponent("projectPage14"),
    developmentOfRepresentationTechniquesAndDesig: makeNodeComponent(
      "developmentOfRepresentationTechniquesAndDesig"
    ),
    listItem4: makeNodeComponent("listItem4"),
    projectPage15: makeNodeComponent("projectPage15"),
    projectPage16: makeNodeComponent("projectPage16"),
    focusOnUnderstandingMaterialityAndConstructio: makeNodeComponent(
      "focusOnUnderstandingMaterialityAndConstructio"
    ),

    // Metadata about props expected for PlasmicNewPage2
    internalVariantProps: PlasmicNewPage2__VariantProps,
    internalArgProps: PlasmicNewPage2__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicNewPage2;
/* prettier-ignore-end */
