/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: s48h5mVi5f22yNVro3eX55

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariants_10L8Baypl3Lf } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 10L8BAYPL3Lf/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariants_10L8Baypl3Lf
});
