/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: s48h5mVi5f22yNVro3eX55
// Component: d3n28mgMlKCD

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: s48h5mVi5f22yNVro3eX55/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: s48h5mVi5f22yNVro3eX55/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: s48h5mVi5f22yNVro3eX55/projectcss
import sty from "./PlasmicNewPage.module.css"; // plasmic-import: d3n28mgMlKCD/css

import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: MHoygwaq8I7H/icon

createPlasmicElementProxy;

export type PlasmicNewPage__VariantMembers = {};
export type PlasmicNewPage__VariantsArgs = {};
type VariantPropType = keyof PlasmicNewPage__VariantsArgs;
export const PlasmicNewPage__VariantProps = new Array<VariantPropType>();

export type PlasmicNewPage__ArgsType = {};
type ArgPropType = keyof PlasmicNewPage__ArgsType;
export const PlasmicNewPage__ArgProps = new Array<ArgPropType>();

export type PlasmicNewPage__OverridesType = {
  root?: Flex__<"div">;
  animatedPortfolioWebsite?: Flex__<"div">;
  container?: Flex__<"div">;
  homePage?: Flex__<"div">;
  homePage2?: Flex__<"div">;
  container2?: Flex__<"div">;
  container3?: Flex__<"div">;
  container4?: Flex__<"div">;
  container5?: Flex__<"div">;
  container6?: Flex__<"div">;
  container7?: Flex__<"div">;
  container8?: Flex__<"div">;
  container9?: Flex__<"div">;
  container10?: Flex__<"div">;
  container11?: Flex__<"div">;
  container12?: Flex__<"div">;
  container13?: Flex__<"div">;
  container14?: Flex__<"div">;
  container15?: Flex__<"div">;
  container16?: Flex__<"div">;
  container17?: Flex__<"div">;
  container18?: Flex__<"div">;
  container19?: Flex__<"div">;
  container20?: Flex__<"div">;
  container21?: Flex__<"div">;
  container22?: Flex__<"div">;
  container23?: Flex__<"div">;
  container24?: Flex__<"div">;
  container25?: Flex__<"div">;
  container26?: Flex__<"div">;
  container27?: Flex__<"div">;
  container28?: Flex__<"div">;
  container29?: Flex__<"div">;
  container30?: Flex__<"div">;
  container31?: Flex__<"div">;
  container32?: Flex__<"div">;
  container33?: Flex__<"div">;
  container34?: Flex__<"div">;
  container35?: Flex__<"div">;
  container36?: Flex__<"div">;
  container37?: Flex__<"div">;
  container38?: Flex__<"div">;
  container39?: Flex__<"div">;
  container40?: Flex__<"div">;
  container41?: Flex__<"div">;
  container42?: Flex__<"div">;
  container43?: Flex__<"div">;
  container44?: Flex__<"div">;
  container45?: Flex__<"div">;
  container46?: Flex__<"div">;
  container47?: Flex__<"div">;
  container48?: Flex__<"div">;
  container49?: Flex__<"div">;
  container50?: Flex__<"div">;
  container51?: Flex__<"div">;
  container52?: Flex__<"div">;
  container53?: Flex__<"div">;
  container54?: Flex__<"div">;
  container55?: Flex__<"div">;
  container56?: Flex__<"div">;
  container57?: Flex__<"div">;
  container58?: Flex__<"div">;
  container59?: Flex__<"div">;
  container60?: Flex__<"div">;
  container61?: Flex__<"div">;
  container62?: Flex__<"div">;
  container63?: Flex__<"div">;
  container64?: Flex__<"div">;
  container65?: Flex__<"div">;
  container66?: Flex__<"div">;
  container67?: Flex__<"div">;
  container68?: Flex__<"div">;
  container69?: Flex__<"div">;
  container70?: Flex__<"div">;
  container71?: Flex__<"div">;
  container72?: Flex__<"div">;
  container73?: Flex__<"div">;
  container74?: Flex__<"div">;
  container75?: Flex__<"div">;
  container76?: Flex__<"div">;
  link?: Flex__<"div">;
  text?: Flex__<"div">;
  link2?: Flex__<"div">;
  text2?: Flex__<"div">;
  link3?: Flex__<"div">;
  text3?: Flex__<"div">;
  link4?: Flex__<"div">;
  text4?: Flex__<"div">;
  link5?: Flex__<"div">;
  text5?: Flex__<"div">;
  link6?: Flex__<"div">;
  text6?: Flex__<"div">;
  link7?: Flex__<"div">;
  text7?: Flex__<"div">;
  link8?: Flex__<"div">;
  text8?: Flex__<"div">;
  heading1?: Flex__<"div">;
  ge?: Flex__<"div">;
  paragraph?: Flex__<"div">;
  container77?: Flex__<"div">;
  svg?: Flex__<"svg">;
  link9?: Flex__<"div">;
};

export interface DefaultNewPageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicNewPage__RenderFunc(props: {
  variants: PlasmicNewPage__VariantsArgs;
  args: PlasmicNewPage__ArgsType;
  overrides: PlasmicNewPage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"animatedPortfolioWebsite"}
            data-plasmic-override={overrides.animatedPortfolioWebsite}
            className={classNames(projectcss.all, sty.animatedPortfolioWebsite)}
          >
            <div
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              className={classNames(projectcss.all, sty.container)}
            >
              <div
                data-plasmic-name={"homePage"}
                data-plasmic-override={overrides.homePage}
                className={classNames(projectcss.all, sty.homePage)}
              />

              <div
                data-plasmic-name={"homePage2"}
                data-plasmic-override={overrides.homePage2}
                className={classNames(projectcss.all, sty.homePage2)}
              />
            </div>
            <div
              data-plasmic-name={"container2"}
              data-plasmic-override={overrides.container2}
              className={classNames(projectcss.all, sty.container2)}
            >
              <div
                data-plasmic-name={"container3"}
                data-plasmic-override={overrides.container3}
                className={classNames(projectcss.all, sty.container3)}
              />

              <div
                data-plasmic-name={"container4"}
                data-plasmic-override={overrides.container4}
                className={classNames(projectcss.all, sty.container4)}
              />

              <div
                data-plasmic-name={"container5"}
                data-plasmic-override={overrides.container5}
                className={classNames(projectcss.all, sty.container5)}
              />

              <div
                data-plasmic-name={"container6"}
                data-plasmic-override={overrides.container6}
                className={classNames(projectcss.all, sty.container6)}
              />

              <div
                data-plasmic-name={"container7"}
                data-plasmic-override={overrides.container7}
                className={classNames(projectcss.all, sty.container7)}
              />

              <div
                data-plasmic-name={"container8"}
                data-plasmic-override={overrides.container8}
                className={classNames(projectcss.all, sty.container8)}
              />

              <div
                data-plasmic-name={"container9"}
                data-plasmic-override={overrides.container9}
                className={classNames(projectcss.all, sty.container9)}
              />

              <div
                data-plasmic-name={"container10"}
                data-plasmic-override={overrides.container10}
                className={classNames(projectcss.all, sty.container10)}
              />

              <div
                data-plasmic-name={"container11"}
                data-plasmic-override={overrides.container11}
                className={classNames(projectcss.all, sty.container11)}
              />

              <div
                data-plasmic-name={"container12"}
                data-plasmic-override={overrides.container12}
                className={classNames(projectcss.all, sty.container12)}
              />

              <div
                data-plasmic-name={"container13"}
                data-plasmic-override={overrides.container13}
                className={classNames(projectcss.all, sty.container13)}
              />

              <div
                data-plasmic-name={"container14"}
                data-plasmic-override={overrides.container14}
                className={classNames(projectcss.all, sty.container14)}
              />

              <div
                data-plasmic-name={"container15"}
                data-plasmic-override={overrides.container15}
                className={classNames(projectcss.all, sty.container15)}
              />

              <div
                data-plasmic-name={"container16"}
                data-plasmic-override={overrides.container16}
                className={classNames(projectcss.all, sty.container16)}
              />

              <div
                data-plasmic-name={"container17"}
                data-plasmic-override={overrides.container17}
                className={classNames(projectcss.all, sty.container17)}
              />

              <div
                data-plasmic-name={"container18"}
                data-plasmic-override={overrides.container18}
                className={classNames(projectcss.all, sty.container18)}
              />

              <div
                data-plasmic-name={"container19"}
                data-plasmic-override={overrides.container19}
                className={classNames(projectcss.all, sty.container19)}
              />

              <div
                data-plasmic-name={"container20"}
                data-plasmic-override={overrides.container20}
                className={classNames(projectcss.all, sty.container20)}
              />

              <div
                data-plasmic-name={"container21"}
                data-plasmic-override={overrides.container21}
                className={classNames(projectcss.all, sty.container21)}
              />

              <div
                data-plasmic-name={"container22"}
                data-plasmic-override={overrides.container22}
                className={classNames(projectcss.all, sty.container22)}
              />

              <div
                data-plasmic-name={"container23"}
                data-plasmic-override={overrides.container23}
                className={classNames(projectcss.all, sty.container23)}
              />

              <div
                data-plasmic-name={"container24"}
                data-plasmic-override={overrides.container24}
                className={classNames(projectcss.all, sty.container24)}
              />

              <div
                data-plasmic-name={"container25"}
                data-plasmic-override={overrides.container25}
                className={classNames(projectcss.all, sty.container25)}
              />

              <div
                data-plasmic-name={"container26"}
                data-plasmic-override={overrides.container26}
                className={classNames(projectcss.all, sty.container26)}
              />

              <div
                data-plasmic-name={"container27"}
                data-plasmic-override={overrides.container27}
                className={classNames(projectcss.all, sty.container27)}
              />

              <div
                data-plasmic-name={"container28"}
                data-plasmic-override={overrides.container28}
                className={classNames(projectcss.all, sty.container28)}
              />

              <div
                data-plasmic-name={"container29"}
                data-plasmic-override={overrides.container29}
                className={classNames(projectcss.all, sty.container29)}
              />

              <div
                data-plasmic-name={"container30"}
                data-plasmic-override={overrides.container30}
                className={classNames(projectcss.all, sty.container30)}
              />

              <div
                data-plasmic-name={"container31"}
                data-plasmic-override={overrides.container31}
                className={classNames(projectcss.all, sty.container31)}
              />

              <div
                data-plasmic-name={"container32"}
                data-plasmic-override={overrides.container32}
                className={classNames(projectcss.all, sty.container32)}
              />

              <div
                data-plasmic-name={"container33"}
                data-plasmic-override={overrides.container33}
                className={classNames(projectcss.all, sty.container33)}
              />

              <div
                data-plasmic-name={"container34"}
                data-plasmic-override={overrides.container34}
                className={classNames(projectcss.all, sty.container34)}
              />

              <div
                data-plasmic-name={"container35"}
                data-plasmic-override={overrides.container35}
                className={classNames(projectcss.all, sty.container35)}
              />

              <div
                data-plasmic-name={"container36"}
                data-plasmic-override={overrides.container36}
                className={classNames(projectcss.all, sty.container36)}
              />

              <div
                data-plasmic-name={"container37"}
                data-plasmic-override={overrides.container37}
                className={classNames(projectcss.all, sty.container37)}
              />

              <div
                data-plasmic-name={"container38"}
                data-plasmic-override={overrides.container38}
                className={classNames(projectcss.all, sty.container38)}
              />

              <div
                data-plasmic-name={"container39"}
                data-plasmic-override={overrides.container39}
                className={classNames(projectcss.all, sty.container39)}
              />

              <div
                data-plasmic-name={"container40"}
                data-plasmic-override={overrides.container40}
                className={classNames(projectcss.all, sty.container40)}
              />

              <div
                data-plasmic-name={"container41"}
                data-plasmic-override={overrides.container41}
                className={classNames(projectcss.all, sty.container41)}
              />

              <div
                data-plasmic-name={"container42"}
                data-plasmic-override={overrides.container42}
                className={classNames(projectcss.all, sty.container42)}
              />

              <div
                data-plasmic-name={"container43"}
                data-plasmic-override={overrides.container43}
                className={classNames(projectcss.all, sty.container43)}
              />

              <div
                data-plasmic-name={"container44"}
                data-plasmic-override={overrides.container44}
                className={classNames(projectcss.all, sty.container44)}
              />

              <div
                data-plasmic-name={"container45"}
                data-plasmic-override={overrides.container45}
                className={classNames(projectcss.all, sty.container45)}
              />

              <div
                data-plasmic-name={"container46"}
                data-plasmic-override={overrides.container46}
                className={classNames(projectcss.all, sty.container46)}
              />

              <div
                data-plasmic-name={"container47"}
                data-plasmic-override={overrides.container47}
                className={classNames(projectcss.all, sty.container47)}
              />

              <div
                data-plasmic-name={"container48"}
                data-plasmic-override={overrides.container48}
                className={classNames(projectcss.all, sty.container48)}
              />

              <div
                data-plasmic-name={"container49"}
                data-plasmic-override={overrides.container49}
                className={classNames(projectcss.all, sty.container49)}
              />

              <div
                data-plasmic-name={"container50"}
                data-plasmic-override={overrides.container50}
                className={classNames(projectcss.all, sty.container50)}
              />

              <div
                data-plasmic-name={"container51"}
                data-plasmic-override={overrides.container51}
                className={classNames(projectcss.all, sty.container51)}
              />

              <div
                data-plasmic-name={"container52"}
                data-plasmic-override={overrides.container52}
                className={classNames(projectcss.all, sty.container52)}
              />

              <div
                data-plasmic-name={"container53"}
                data-plasmic-override={overrides.container53}
                className={classNames(projectcss.all, sty.container53)}
              />

              <div
                data-plasmic-name={"container54"}
                data-plasmic-override={overrides.container54}
                className={classNames(projectcss.all, sty.container54)}
              />

              <div
                data-plasmic-name={"container55"}
                data-plasmic-override={overrides.container55}
                className={classNames(projectcss.all, sty.container55)}
              />

              <div
                data-plasmic-name={"container56"}
                data-plasmic-override={overrides.container56}
                className={classNames(projectcss.all, sty.container56)}
              />

              <div
                data-plasmic-name={"container57"}
                data-plasmic-override={overrides.container57}
                className={classNames(projectcss.all, sty.container57)}
              />

              <div
                data-plasmic-name={"container58"}
                data-plasmic-override={overrides.container58}
                className={classNames(projectcss.all, sty.container58)}
              />

              <div
                data-plasmic-name={"container59"}
                data-plasmic-override={overrides.container59}
                className={classNames(projectcss.all, sty.container59)}
              />

              <div
                data-plasmic-name={"container60"}
                data-plasmic-override={overrides.container60}
                className={classNames(projectcss.all, sty.container60)}
              />

              <div
                data-plasmic-name={"container61"}
                data-plasmic-override={overrides.container61}
                className={classNames(projectcss.all, sty.container61)}
              />

              <div
                data-plasmic-name={"container62"}
                data-plasmic-override={overrides.container62}
                className={classNames(projectcss.all, sty.container62)}
              />

              <div
                data-plasmic-name={"container63"}
                data-plasmic-override={overrides.container63}
                className={classNames(projectcss.all, sty.container63)}
              />

              <div
                data-plasmic-name={"container64"}
                data-plasmic-override={overrides.container64}
                className={classNames(projectcss.all, sty.container64)}
              />

              <div
                data-plasmic-name={"container65"}
                data-plasmic-override={overrides.container65}
                className={classNames(projectcss.all, sty.container65)}
              />

              <div
                data-plasmic-name={"container66"}
                data-plasmic-override={overrides.container66}
                className={classNames(projectcss.all, sty.container66)}
              />

              <div
                data-plasmic-name={"container67"}
                data-plasmic-override={overrides.container67}
                className={classNames(projectcss.all, sty.container67)}
              />

              <div
                data-plasmic-name={"container68"}
                data-plasmic-override={overrides.container68}
                className={classNames(projectcss.all, sty.container68)}
              />

              <div
                data-plasmic-name={"container69"}
                data-plasmic-override={overrides.container69}
                className={classNames(projectcss.all, sty.container69)}
              />

              <div
                data-plasmic-name={"container70"}
                data-plasmic-override={overrides.container70}
                className={classNames(projectcss.all, sty.container70)}
              />

              <div
                data-plasmic-name={"container71"}
                data-plasmic-override={overrides.container71}
                className={classNames(projectcss.all, sty.container71)}
              />

              <div
                data-plasmic-name={"container72"}
                data-plasmic-override={overrides.container72}
                className={classNames(projectcss.all, sty.container72)}
              />

              <div
                data-plasmic-name={"container73"}
                data-plasmic-override={overrides.container73}
                className={classNames(projectcss.all, sty.container73)}
              />

              <div
                data-plasmic-name={"container74"}
                data-plasmic-override={overrides.container74}
                className={classNames(projectcss.all, sty.container74)}
              />
            </div>
            <div
              data-plasmic-name={"container75"}
              data-plasmic-override={overrides.container75}
              className={classNames(projectcss.all, sty.container75)}
            >
              <div
                data-plasmic-name={"container76"}
                data-plasmic-override={overrides.container76}
                className={classNames(projectcss.all, sty.container76)}
              >
                <div
                  data-plasmic-name={"link"}
                  data-plasmic-override={overrides.link}
                  className={classNames(projectcss.all, sty.link)}
                >
                  <div
                    data-plasmic-name={"text"}
                    data-plasmic-override={overrides.text}
                    className={classNames(projectcss.all, sty.text)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___3QjYn
                      )}
                    >
                      {"stage 1 work"}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"link2"}
                  data-plasmic-override={overrides.link2}
                  className={classNames(projectcss.all, sty.link2)}
                >
                  <div
                    data-plasmic-name={"text2"}
                    data-plasmic-override={overrides.text2}
                    className={classNames(projectcss.all, sty.text2)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___7RA3P
                      )}
                    >
                      {"essays and writing"}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"link3"}
                  data-plasmic-override={overrides.link3}
                  className={classNames(projectcss.all, sty.link3)}
                >
                  <div
                    data-plasmic-name={"text3"}
                    data-plasmic-override={overrides.text3}
                    className={classNames(projectcss.all, sty.text3)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__bp0Pf
                      )}
                    >
                      {"stage 2 work"}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"link4"}
                  data-plasmic-override={overrides.link4}
                  className={classNames(projectcss.all, sty.link4)}
                >
                  <div
                    data-plasmic-name={"text4"}
                    data-plasmic-override={overrides.text4}
                    className={classNames(projectcss.all, sty.text4)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pRz00
                      )}
                    >
                      {"orchard road studios"}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"link5"}
                  data-plasmic-override={overrides.link5}
                  className={classNames(projectcss.all, sty.link5)}
                >
                  <div
                    data-plasmic-name={"text5"}
                    data-plasmic-override={overrides.text5}
                    className={classNames(projectcss.all, sty.text5)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__idF0Y
                      )}
                    >
                      {"lifelong learning retreat"}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"link6"}
                  data-plasmic-override={overrides.link6}
                  className={classNames(projectcss.all, sty.link6)}
                >
                  <div
                    data-plasmic-name={"text6"}
                    data-plasmic-override={overrides.text6}
                    className={classNames(projectcss.all, sty.text6)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__nqqI2
                      )}
                    >
                      {"technical work"}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"link7"}
                  data-plasmic-override={overrides.link7}
                  className={classNames(projectcss.all, sty.link7)}
                >
                  <div
                    data-plasmic-name={"text7"}
                    data-plasmic-override={overrides.text7}
                    className={classNames(projectcss.all, sty.text7)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__bAwu
                      )}
                    >
                      {"video work"}
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"link8"}
                  data-plasmic-override={overrides.link8}
                  className={classNames(projectcss.all, sty.link8)}
                >
                  <div
                    data-plasmic-name={"text8"}
                    data-plasmic-override={overrides.text8}
                    className={classNames(projectcss.all, sty.text8)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jdEiu
                      )}
                    >
                      {"work on exchange"}
                    </div>
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"heading1"}
                data-plasmic-override={overrides.heading1}
                className={classNames(projectcss.all, sty.heading1)}
              >
                <div
                  data-plasmic-name={"ge"}
                  data-plasmic-override={overrides.ge}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.ge
                  )}
                >
                  {"Erika"}
                </div>
              </div>
              <div
                data-plasmic-name={"paragraph"}
                data-plasmic-override={overrides.paragraph}
                className={classNames(projectcss.all, sty.paragraph)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__sm6A0
                  )}
                >
                  {"Student Works"}
                </div>
              </div>
              <div
                data-plasmic-name={"container77"}
                data-plasmic-override={overrides.container77}
                className={classNames(projectcss.all, sty.container77)}
              >
                <Icon4Icon
                  data-plasmic-name={"svg"}
                  data-plasmic-override={overrides.svg}
                  className={classNames(projectcss.all, sty.svg)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"link9"}
                  data-plasmic-override={overrides.link9}
                  className={classNames(projectcss.all, sty.link9)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ueRYc
                    )}
                  >
                    {"edward.christie@example.com"}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "animatedPortfolioWebsite",
    "container",
    "homePage",
    "homePage2",
    "container2",
    "container3",
    "container4",
    "container5",
    "container6",
    "container7",
    "container8",
    "container9",
    "container10",
    "container11",
    "container12",
    "container13",
    "container14",
    "container15",
    "container16",
    "container17",
    "container18",
    "container19",
    "container20",
    "container21",
    "container22",
    "container23",
    "container24",
    "container25",
    "container26",
    "container27",
    "container28",
    "container29",
    "container30",
    "container31",
    "container32",
    "container33",
    "container34",
    "container35",
    "container36",
    "container37",
    "container38",
    "container39",
    "container40",
    "container41",
    "container42",
    "container43",
    "container44",
    "container45",
    "container46",
    "container47",
    "container48",
    "container49",
    "container50",
    "container51",
    "container52",
    "container53",
    "container54",
    "container55",
    "container56",
    "container57",
    "container58",
    "container59",
    "container60",
    "container61",
    "container62",
    "container63",
    "container64",
    "container65",
    "container66",
    "container67",
    "container68",
    "container69",
    "container70",
    "container71",
    "container72",
    "container73",
    "container74",
    "container75",
    "container76",
    "link",
    "text",
    "link2",
    "text2",
    "link3",
    "text3",
    "link4",
    "text4",
    "link5",
    "text5",
    "link6",
    "text6",
    "link7",
    "text7",
    "link8",
    "text8",
    "heading1",
    "ge",
    "paragraph",
    "container77",
    "svg",
    "link9"
  ],
  animatedPortfolioWebsite: [
    "animatedPortfolioWebsite",
    "container",
    "homePage",
    "homePage2",
    "container2",
    "container3",
    "container4",
    "container5",
    "container6",
    "container7",
    "container8",
    "container9",
    "container10",
    "container11",
    "container12",
    "container13",
    "container14",
    "container15",
    "container16",
    "container17",
    "container18",
    "container19",
    "container20",
    "container21",
    "container22",
    "container23",
    "container24",
    "container25",
    "container26",
    "container27",
    "container28",
    "container29",
    "container30",
    "container31",
    "container32",
    "container33",
    "container34",
    "container35",
    "container36",
    "container37",
    "container38",
    "container39",
    "container40",
    "container41",
    "container42",
    "container43",
    "container44",
    "container45",
    "container46",
    "container47",
    "container48",
    "container49",
    "container50",
    "container51",
    "container52",
    "container53",
    "container54",
    "container55",
    "container56",
    "container57",
    "container58",
    "container59",
    "container60",
    "container61",
    "container62",
    "container63",
    "container64",
    "container65",
    "container66",
    "container67",
    "container68",
    "container69",
    "container70",
    "container71",
    "container72",
    "container73",
    "container74",
    "container75",
    "container76",
    "link",
    "text",
    "link2",
    "text2",
    "link3",
    "text3",
    "link4",
    "text4",
    "link5",
    "text5",
    "link6",
    "text6",
    "link7",
    "text7",
    "link8",
    "text8",
    "heading1",
    "ge",
    "paragraph",
    "container77",
    "svg",
    "link9"
  ],
  container: ["container", "homePage", "homePage2"],
  homePage: ["homePage"],
  homePage2: ["homePage2"],
  container2: [
    "container2",
    "container3",
    "container4",
    "container5",
    "container6",
    "container7",
    "container8",
    "container9",
    "container10",
    "container11",
    "container12",
    "container13",
    "container14",
    "container15",
    "container16",
    "container17",
    "container18",
    "container19",
    "container20",
    "container21",
    "container22",
    "container23",
    "container24",
    "container25",
    "container26",
    "container27",
    "container28",
    "container29",
    "container30",
    "container31",
    "container32",
    "container33",
    "container34",
    "container35",
    "container36",
    "container37",
    "container38",
    "container39",
    "container40",
    "container41",
    "container42",
    "container43",
    "container44",
    "container45",
    "container46",
    "container47",
    "container48",
    "container49",
    "container50",
    "container51",
    "container52",
    "container53",
    "container54",
    "container55",
    "container56",
    "container57",
    "container58",
    "container59",
    "container60",
    "container61",
    "container62",
    "container63",
    "container64",
    "container65",
    "container66",
    "container67",
    "container68",
    "container69",
    "container70",
    "container71",
    "container72",
    "container73",
    "container74"
  ],
  container3: ["container3"],
  container4: ["container4"],
  container5: ["container5"],
  container6: ["container6"],
  container7: ["container7"],
  container8: ["container8"],
  container9: ["container9"],
  container10: ["container10"],
  container11: ["container11"],
  container12: ["container12"],
  container13: ["container13"],
  container14: ["container14"],
  container15: ["container15"],
  container16: ["container16"],
  container17: ["container17"],
  container18: ["container18"],
  container19: ["container19"],
  container20: ["container20"],
  container21: ["container21"],
  container22: ["container22"],
  container23: ["container23"],
  container24: ["container24"],
  container25: ["container25"],
  container26: ["container26"],
  container27: ["container27"],
  container28: ["container28"],
  container29: ["container29"],
  container30: ["container30"],
  container31: ["container31"],
  container32: ["container32"],
  container33: ["container33"],
  container34: ["container34"],
  container35: ["container35"],
  container36: ["container36"],
  container37: ["container37"],
  container38: ["container38"],
  container39: ["container39"],
  container40: ["container40"],
  container41: ["container41"],
  container42: ["container42"],
  container43: ["container43"],
  container44: ["container44"],
  container45: ["container45"],
  container46: ["container46"],
  container47: ["container47"],
  container48: ["container48"],
  container49: ["container49"],
  container50: ["container50"],
  container51: ["container51"],
  container52: ["container52"],
  container53: ["container53"],
  container54: ["container54"],
  container55: ["container55"],
  container56: ["container56"],
  container57: ["container57"],
  container58: ["container58"],
  container59: ["container59"],
  container60: ["container60"],
  container61: ["container61"],
  container62: ["container62"],
  container63: ["container63"],
  container64: ["container64"],
  container65: ["container65"],
  container66: ["container66"],
  container67: ["container67"],
  container68: ["container68"],
  container69: ["container69"],
  container70: ["container70"],
  container71: ["container71"],
  container72: ["container72"],
  container73: ["container73"],
  container74: ["container74"],
  container75: [
    "container75",
    "container76",
    "link",
    "text",
    "link2",
    "text2",
    "link3",
    "text3",
    "link4",
    "text4",
    "link5",
    "text5",
    "link6",
    "text6",
    "link7",
    "text7",
    "link8",
    "text8",
    "heading1",
    "ge",
    "paragraph",
    "container77",
    "svg",
    "link9"
  ],
  container76: [
    "container76",
    "link",
    "text",
    "link2",
    "text2",
    "link3",
    "text3",
    "link4",
    "text4",
    "link5",
    "text5",
    "link6",
    "text6",
    "link7",
    "text7",
    "link8",
    "text8"
  ],
  link: ["link", "text"],
  text: ["text"],
  link2: ["link2", "text2"],
  text2: ["text2"],
  link3: ["link3", "text3"],
  text3: ["text3"],
  link4: ["link4", "text4"],
  text4: ["text4"],
  link5: ["link5", "text5"],
  text5: ["text5"],
  link6: ["link6", "text6"],
  text6: ["text6"],
  link7: ["link7", "text7"],
  text7: ["text7"],
  link8: ["link8", "text8"],
  text8: ["text8"],
  heading1: ["heading1", "ge"],
  ge: ["ge"],
  paragraph: ["paragraph"],
  container77: ["container77", "svg", "link9"],
  svg: ["svg"],
  link9: ["link9"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  animatedPortfolioWebsite: "div";
  container: "div";
  homePage: "div";
  homePage2: "div";
  container2: "div";
  container3: "div";
  container4: "div";
  container5: "div";
  container6: "div";
  container7: "div";
  container8: "div";
  container9: "div";
  container10: "div";
  container11: "div";
  container12: "div";
  container13: "div";
  container14: "div";
  container15: "div";
  container16: "div";
  container17: "div";
  container18: "div";
  container19: "div";
  container20: "div";
  container21: "div";
  container22: "div";
  container23: "div";
  container24: "div";
  container25: "div";
  container26: "div";
  container27: "div";
  container28: "div";
  container29: "div";
  container30: "div";
  container31: "div";
  container32: "div";
  container33: "div";
  container34: "div";
  container35: "div";
  container36: "div";
  container37: "div";
  container38: "div";
  container39: "div";
  container40: "div";
  container41: "div";
  container42: "div";
  container43: "div";
  container44: "div";
  container45: "div";
  container46: "div";
  container47: "div";
  container48: "div";
  container49: "div";
  container50: "div";
  container51: "div";
  container52: "div";
  container53: "div";
  container54: "div";
  container55: "div";
  container56: "div";
  container57: "div";
  container58: "div";
  container59: "div";
  container60: "div";
  container61: "div";
  container62: "div";
  container63: "div";
  container64: "div";
  container65: "div";
  container66: "div";
  container67: "div";
  container68: "div";
  container69: "div";
  container70: "div";
  container71: "div";
  container72: "div";
  container73: "div";
  container74: "div";
  container75: "div";
  container76: "div";
  link: "div";
  text: "div";
  link2: "div";
  text2: "div";
  link3: "div";
  text3: "div";
  link4: "div";
  text4: "div";
  link5: "div";
  text5: "div";
  link6: "div";
  text6: "div";
  link7: "div";
  text7: "div";
  link8: "div";
  text8: "div";
  heading1: "div";
  ge: "div";
  paragraph: "div";
  container77: "div";
  svg: "svg";
  link9: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNewPage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNewPage__VariantsArgs;
    args?: PlasmicNewPage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicNewPage__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicNewPage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicNewPage__ArgProps,
          internalVariantPropNames: PlasmicNewPage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNewPage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNewPage";
  } else {
    func.displayName = `PlasmicNewPage.${nodeName}`;
  }
  return func;
}

export const PlasmicNewPage = Object.assign(
  // Top-level PlasmicNewPage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    animatedPortfolioWebsite: makeNodeComponent("animatedPortfolioWebsite"),
    container: makeNodeComponent("container"),
    homePage: makeNodeComponent("homePage"),
    homePage2: makeNodeComponent("homePage2"),
    container2: makeNodeComponent("container2"),
    container3: makeNodeComponent("container3"),
    container4: makeNodeComponent("container4"),
    container5: makeNodeComponent("container5"),
    container6: makeNodeComponent("container6"),
    container7: makeNodeComponent("container7"),
    container8: makeNodeComponent("container8"),
    container9: makeNodeComponent("container9"),
    container10: makeNodeComponent("container10"),
    container11: makeNodeComponent("container11"),
    container12: makeNodeComponent("container12"),
    container13: makeNodeComponent("container13"),
    container14: makeNodeComponent("container14"),
    container15: makeNodeComponent("container15"),
    container16: makeNodeComponent("container16"),
    container17: makeNodeComponent("container17"),
    container18: makeNodeComponent("container18"),
    container19: makeNodeComponent("container19"),
    container20: makeNodeComponent("container20"),
    container21: makeNodeComponent("container21"),
    container22: makeNodeComponent("container22"),
    container23: makeNodeComponent("container23"),
    container24: makeNodeComponent("container24"),
    container25: makeNodeComponent("container25"),
    container26: makeNodeComponent("container26"),
    container27: makeNodeComponent("container27"),
    container28: makeNodeComponent("container28"),
    container29: makeNodeComponent("container29"),
    container30: makeNodeComponent("container30"),
    container31: makeNodeComponent("container31"),
    container32: makeNodeComponent("container32"),
    container33: makeNodeComponent("container33"),
    container34: makeNodeComponent("container34"),
    container35: makeNodeComponent("container35"),
    container36: makeNodeComponent("container36"),
    container37: makeNodeComponent("container37"),
    container38: makeNodeComponent("container38"),
    container39: makeNodeComponent("container39"),
    container40: makeNodeComponent("container40"),
    container41: makeNodeComponent("container41"),
    container42: makeNodeComponent("container42"),
    container43: makeNodeComponent("container43"),
    container44: makeNodeComponent("container44"),
    container45: makeNodeComponent("container45"),
    container46: makeNodeComponent("container46"),
    container47: makeNodeComponent("container47"),
    container48: makeNodeComponent("container48"),
    container49: makeNodeComponent("container49"),
    container50: makeNodeComponent("container50"),
    container51: makeNodeComponent("container51"),
    container52: makeNodeComponent("container52"),
    container53: makeNodeComponent("container53"),
    container54: makeNodeComponent("container54"),
    container55: makeNodeComponent("container55"),
    container56: makeNodeComponent("container56"),
    container57: makeNodeComponent("container57"),
    container58: makeNodeComponent("container58"),
    container59: makeNodeComponent("container59"),
    container60: makeNodeComponent("container60"),
    container61: makeNodeComponent("container61"),
    container62: makeNodeComponent("container62"),
    container63: makeNodeComponent("container63"),
    container64: makeNodeComponent("container64"),
    container65: makeNodeComponent("container65"),
    container66: makeNodeComponent("container66"),
    container67: makeNodeComponent("container67"),
    container68: makeNodeComponent("container68"),
    container69: makeNodeComponent("container69"),
    container70: makeNodeComponent("container70"),
    container71: makeNodeComponent("container71"),
    container72: makeNodeComponent("container72"),
    container73: makeNodeComponent("container73"),
    container74: makeNodeComponent("container74"),
    container75: makeNodeComponent("container75"),
    container76: makeNodeComponent("container76"),
    link: makeNodeComponent("link"),
    text: makeNodeComponent("text"),
    link2: makeNodeComponent("link2"),
    text2: makeNodeComponent("text2"),
    link3: makeNodeComponent("link3"),
    text3: makeNodeComponent("text3"),
    link4: makeNodeComponent("link4"),
    text4: makeNodeComponent("text4"),
    link5: makeNodeComponent("link5"),
    text5: makeNodeComponent("text5"),
    link6: makeNodeComponent("link6"),
    text6: makeNodeComponent("text6"),
    link7: makeNodeComponent("link7"),
    text7: makeNodeComponent("text7"),
    link8: makeNodeComponent("link8"),
    text8: makeNodeComponent("text8"),
    heading1: makeNodeComponent("heading1"),
    ge: makeNodeComponent("ge"),
    paragraph: makeNodeComponent("paragraph"),
    container77: makeNodeComponent("container77"),
    svg: makeNodeComponent("svg"),
    link9: makeNodeComponent("link9"),

    // Metadata about props expected for PlasmicNewPage
    internalVariantProps: PlasmicNewPage__VariantProps,
    internalArgProps: PlasmicNewPage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicNewPage;
/* prettier-ignore-end */
