/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: s48h5mVi5f22yNVro3eX55

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: s48h5mVi5f22yNVro3eX55/projectModule

import projectcss from "./plasmic.module.css"; // plasmic-import: s48h5mVi5f22yNVro3eX55/projectcss

const data = {
  base: `${projectcss.plasmic_tokens}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
